NumPy + Pandas para el Examen

Este notebook contiene TODAS las funciones que necesitas saber, organizadas por categorías y con ejemplos prácticos.

## 🔧 1. IMPORTACIONES

In [15]:
# Importaciones estándar
import numpy as np
import pandas as pd
import numpy.linalg as linalg
import math
import os
import random

---
# 🔵 2. NUMPY (`np`)

## 2.1 Creación de arrays

In [3]:
# 📌 np.array() - Crea un array desde una lista/tupla
print("=== np.array() ===")
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([[1, 2], [3, 4]])  # 2D
print("1D:", arr1)
print("2D:\n", arr2)
print()

# 📌 np.arange() - Secuencia de números (similar a range)
print("=== np.arange() ===")
print("np.arange(5):", np.arange(5))           # 0,1,2,3,4
print("np.arange(2,10,2):", np.arange(2,10,2)) # 2,4,6,8
print("np.arange(2,10,2.1):", np.arange(2,10,2.1))  # Con floats
print()

# 📌 np.zeros() - Array lleno de ceros
print("=== np.zeros() ===")
print("np.zeros(3):", np.zeros(3))
print("np.zeros((2,3)):\n", np.zeros((2,3)))
print()

# 📌 np.ones() - Array lleno de unos
print("=== np.ones() ===")
print("np.ones(4):", np.ones(4))
print("np.ones((2,2)):\n", np.ones((2,2)))
print()

# 📌 np.full() - Array lleno de un valor específico
print("=== np.full() ===")
print("np.full((3,2), 7):\n", np.full((3,2), 7))
print()

# 📌 np.eye() - Matriz identidad
print("=== np.eye() ===")
print("np.eye(3):\n", np.eye(3))
print()

# 📌 np.empty() - Array sin inicializar (contiene basura)
print("=== np.empty() ===")
print("np.empty((2,2)):\n", np.empty((2,2)))
print("⚠️ Los valores son basura de memoria, no te fíes")

=== np.array() ===
1D: [1 2 3 4 5]
2D:
 [[1 2]
 [3 4]]

=== np.arange() ===
np.arange(5): [0 1 2 3 4]
np.arange(2,10,2): [2 4 6 8]
np.arange(2,10,2.1): [2.  4.1 6.2 8.3]

=== np.zeros() ===
np.zeros(3): [0. 0. 0.]
np.zeros((2,3)):
 [[0. 0. 0.]
 [0. 0. 0.]]

=== np.ones() ===
np.ones(4): [1. 1. 1. 1.]
np.ones((2,2)):
 [[1. 1.]
 [1. 1.]]

=== np.full() ===
np.full((3,2), 7):
 [[7 7]
 [7 7]
 [7 7]]

=== np.eye() ===
np.eye(3):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

=== np.empty() ===
np.empty((2,2)):
 [[1. 1.]
 [1. 1.]]
⚠️ Los valores son basura de memoria, no te fíes

In [4]:
# 📌 np.random.randint() - Enteros aleatorios
print("=== np.random.randint() ===")
print("np.random.randint(10):", np.random.randint(10))  # 0-9
print("np.random.randint(5, 15):", np.random.randint(5, 15))  # 5-14
print("np.random.randint(0, 10, size=(2,3)):\n", np.random.randint(0, 10, size=(2,3)))
print()

# 📌 np.random.rand() - Floats aleatorios [0,1)
print("=== np.random.rand() ===")
print("np.random.rand():\n", np.random.rand())
print("np.random.rand(2,3):\n", np.random.rand(2,3))
print()

# 📌 np.random.randn() - Distribución normal estándar
print("=== np.random.randn() ===")
print("np.random.randn(2,3):\n", np.random.randn(2,3))
print()

# 📌 np.random.seed() - Fija la semilla para reproducibilidad
print("=== np.random.seed() ===")
np.random.seed(42)
print("Con seed(42), randint siempre da el mismo:", np.random.randint(0, 10))  # Siempre 6
print()

# 📌 np.linspace() - Puntos espaciados uniformemente
print("=== np.linspace() ===")
print("np.linspace(0, 1, 5):", np.linspace(0, 1, 5))  # 0, 0.25, 0.5, 0.75, 1

=== np.random.randint() ===
np.random.randint(10): 0
np.random.randint(5, 15): 6
np.random.randint(0, 10, size=(2,3)):
 [[2 7 4]
 [9 8 9]]

=== np.random.rand() ===
np.random.rand():
 0.8279950572377097
np.random.rand(2,3):
 [[0.47266557 0.99982281 0.64704063]
 [0.99155853 0.44923621 0.87011258]]

=== np.random.randn() ===
np.random.randn(2,3):
 [[ 0.9650771   1.2697915  -0.39294596]
 [ 0.63276063  0.19928993 -0.55028134]]

=== np.random.seed() ===
Con seed(42), randint siempre da el mismo: 6

=== np.linspace() ===
np.linspace(0, 1, 5): [0.   0.25 0.5  0.75 1.  ]

## 2.2 Información del array

In [5]:
# Creamos un array de prueba
arr = np.array([4, 2, 7, 1, 9, 3, 5])
arr2d = np.array([[1, 2, 3], [4, 5, 6]])

print("=== Array de prueba ===")
print("arr:", arr)
print("arr2d:\n", arr2d)
print()

# 📌 .shape - Dimensiones
print("=== .shape ===")
print("arr.shape:", arr.shape)  # (7,)
print("arr2d.shape:", arr2d.shape)  # (2,3)
print()

# 📌 .size - Número total de elementos
print("=== .size ===")
print("arr.size:", arr.size)  # 7
print("arr2d.size:", arr2d.size)  # 6
print()

# 📌 .ndim - Número de dimensiones
print("=== .ndim ===")
print("arr.ndim:", arr.ndim)  # 1
print("arr2d.ndim:", arr2d.ndim)  # 2
print()

# 📌 .dtype - Tipo de datos
print("=== .dtype ===")
print("arr.dtype:", arr.dtype)
print()

# 📌 .argmax() / .argmin() - Índice del valor máx/mín
print("=== .argmax() / .argmin() ===")
print("arr.argmax():", arr.argmax())  # Índice del 9 → 4
print("arr.argmin():", arr.argmin())  # Índice del 1 → 3
print()

# 📌 np.amax() / np.amin() - Valor máx/mín
print("=== np.amax() / np.amin() ===")
print("np.amax(arr):", np.amax(arr))  # 9
print("np.amin(arr):", np.amin(arr))  # 1
print()

# 📌 .nonzero() - Índices de elementos ≠ 0
arr_ceros = np.array([0, 4, 0, 7, 0, 2])
print("=== .nonzero() ===")
print("arr_ceros:", arr_ceros)
print("arr_ceros.nonzero():", arr_ceros.nonzero())  # (1, 3, 5)

=== Array de prueba ===
arr: [4 2 7 1 9 3 5]
arr2d:
 [[1 2 3]
 [4 5 6]]

=== .shape ===
arr.shape: (7,)
arr2d.shape: (2, 3)

=== .size ===
arr.size: 7
arr2d.size: 6

=== .ndim ===
arr.ndim: 1
arr2d.ndim: 2

=== .dtype ===
arr.dtype: int64

=== .argmax() / .argmin() ===
arr.argmax(): 4
arr.argmin(): 3

=== np.amax() / np.amin() ===
np.amax(arr): 9
np.amin(arr): 1

=== .nonzero() ===
arr_ceros: [0 4 0 7 0 2]
arr_ceros.nonzero(): (array([1, 3, 5]),)

## 2.3 Manipulación y redimensionado

In [6]:
# Crear array de prueba
arr = np.arange(12)  # [0,1,2,3,4,5,6,7,8,9,10,11]
print("=== Array original ===")
print("arr:", arr)
print()

# 📌 .reshape() - Cambia la forma del array
print("=== .reshape() ===")
print("arr.reshape(3,4):\n", arr.reshape(3,4))
print("arr.reshape(2, -1):\n", arr.reshape(2, -1))  # -1 infiere automáticamente
print()

# 📌 .flatten() - Convierte a 1D (copia)
print("=== .flatten() ===")
matriz = np.arange(9).reshape(3,3)
print("matriz:\n", matriz)
print("matriz.flatten():", matriz.flatten())
print()

# 📌 .swapaxes() - Intercambia ejes
print("=== .swapaxes() ===")
print("matriz.swapaxes(0, 1):\n", matriz.swapaxes(0, 1))  # Transpuesta
print()

# 📌 .T o np.transpose() - Transpuesta
print("=== .T / np.transpose() ===")
print("matriz.T:\n", matriz.T)
print()

# 📌 np.flip() - Invierte el orden
print("=== np.flip() ===")
print("np.flip(arr):", np.flip(arr))
print("np.flip(matriz, axis=0):\n", np.flip(matriz, axis=0))  # Invierte filas
print()

# 📌 .sort() - Ordena in-place
print("=== .sort() ===")
desordenado = np.array([5, 2, 8, 1, 9, 3])
desordenado.sort()
print("desordenado.sort():\n", desordenado)  # [1,2,3,5,8,9]

=== Array original ===
arr: [ 0  1  2  3  4  5  6  7  8  9 10 11]

=== .reshape() ===
arr.reshape(3,4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
arr.reshape(2, -1):
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

=== .flatten() ===
matriz:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
matriz.flatten(): [0 1 2 3 4 5 6 7 8]

=== .swapaxes() ===
matriz.swapaxes(0, 1):
 [[0 3 6]
 [1 4 7]
 [2 5 8]]

=== .T / np.transpose() ===
matriz.T:
 [[0 3 6]
 [1 4 7]
 [2 5 8]]

=== np.flip() ===
np.flip(arr): [11 10  9  8  7  6  5  4  3  2  1  0]
np.flip(matriz, axis=0):
 [[6 7 8]
 [3 4 5]
 [0 1 2]]

=== .sort() ===
desordenado.sort():
 [1 2 3 5 8 9]

## 2.4 Concatenación y división

In [7]:
# Arrays de prueba
a = np.array([0, 0, 0])
b = np.array([1, 1, 1])
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("=== Arrays de prueba ===")
print("a:", a)
print("b:", b)
print("A:\n", A)
print("B:\n", B)
print()

# 📌 np.hstack() - Apila horizontalmente
print("=== np.hstack() ===")
print("np.hstack((a, b)):", np.hstack((a, b)))  # [0,0,0,1,1,1]
print()

# 📌 np.vstack() - Apila verticalmente
print("=== np.vstack() ===")
print("np.vstack((a, b)):\n", np.vstack((a, b)))
print()

# 📌 np.concatenate() - Concatena con eje
print("=== np.concatenate() ===")
print("np.concatenate((A, B), axis=0):\n", np.concatenate((A, B), axis=0))  # Por filas
print("np.concatenate((A, B), axis=1):\n", np.concatenate((A, B), axis=1))  # Por columnas
print()

# 📌 np.array_split() - Divide en partes
print("=== np.array_split() ===")
arr = np.arange(16).reshape(4,4)
print("arr:\n", arr)
partes = np.array_split(arr, 2, axis=0)  # Divide por filas en 2 partes
print("np.array_split(arr, 2, axis=0):")
for i, parte in enumerate(partes):
    print(f"Parte {i}:\n{parte}")

=== Arrays de prueba ===
a: [0 0 0]
b: [1 1 1]
A:
 [[1 2]
 [3 4]]
B:
 [[5 6]
 [7 8]]

=== np.hstack() ===
np.hstack((a, b)): [0 0 0 1 1 1]

=== np.vstack() ===
np.vstack((a, b)):
 [[0 0 0]
 [1 1 1]]

=== np.concatenate() ===
np.concatenate((A, B), axis=0):
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
np.concatenate((A, B), axis=1):
 [[1 2 5 6]
 [3 4 7 8]]

=== np.array_split() ===
arr:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
np.array_split(arr, 2, axis=0):
Parte 0:
[[0 1 2 3]
 [4 5 6 7]]
Parte 1:
[[ 8  9 10 11]
 [12 13 14 15]]

## 2.5 Operaciones matemáticas y estadísticas

In [8]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print("=== Array de prueba ===")
print("arr:", arr)
print()

# 📌 np.sum() / .sum() - Suma todos los elementos
print("=== .sum() ===")
print("arr.sum():", arr.sum())  # 45
print()

# 📌 .cumsum() - Suma acumulada
print("=== .cumsum() ===")
print("arr.cumsum():", arr.cumsum())  # [1,3,6,10,15,21,28,36,45]
print()

# 📌 np.mean() / .mean() - Media
print("=== .mean() ===")
print("arr.mean():", arr.mean())  # 5.0
print()

# 📌 np.std() / .std() - Desviación estándar
print("=== .std() ===")
print("arr.std():", arr.std())
print()

# 📌 np.sqrt() - Raíz cuadrada
print("=== np.sqrt() ===")
print("np.sqrt(arr):", np.sqrt(arr))
print()

# 📌 np.exp() - Exponencial
print("=== np.exp() ===")
print("np.exp(arr[:3]):", np.exp(arr[:3]))
print()

# 📌 np.log() - Logaritmo natural
print("=== np.log() ===")
print("np.log(arr[1:4]):", np.log(arr[1:4]))
print()

# 📌 .any() / np.any() - ¿Algún True?
print("=== .any() ===")
arr_bool = np.array([False, False, True, False])
print("arr_bool.any():", arr_bool.any())  # True
print()

# 📌 .all() / np.all() - ¿Todos True?
print("=== .all() ===")
arr_bool2 = np.array([True, True, True])
print("arr_bool2.all():", arr_bool2.all())  # True
print()

# 📌 np.unique() - Valores únicos
print("=== np.unique() ===")
arr_duplicado = np.array([1, 2, 2, 3, 4, 4, 4, 5])
print("np.unique(arr_duplicado):", np.unique(arr_duplicado))  # [1,2,3,4,5]
print()

# 📌 np.isnan() - Detecta NaN
print("=== np.isnan() ===")
arr_nan = np.array([1, np.nan, 3, np.nan, 5])
print("np.isnan(arr_nan):", np.isnan(arr_nan))  # [False, True, False, True, False]

=== Array de prueba ===
arr: [1 2 3 4 5 6 7 8 9]

=== .sum() ===
arr.sum(): 45

=== .cumsum() ===
arr.cumsum(): [ 1  3  6 10 15 21 28 36 45]

=== .mean() ===
arr.mean(): 5.0

=== .std() ===
arr.std(): 2.581988897471611

=== np.sqrt() ===
np.sqrt(arr): [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.        ]

=== np.exp() ===
np.exp(arr[:3]): [ 2.71828183  7.3890561  20.08553692]

=== np.log() ===
np.log(arr[1:4]): [0.69314718 1.09861229 1.38629436]

=== .any() ===
arr_bool.any(): True

=== .all() ===
arr_bool2.all(): True

=== np.unique() ===
np.unique(arr_duplicado): [1 2 3 4 5]

=== np.isnan() ===
np.isnan(arr_nan): [False  True False  True False]

## 2.6 Álgebra lineal (`np.linalg`)

In [9]:
import numpy.linalg as linalg

# 📌 np.linalg.solve() - Resuelve sistemas Ax = b
print("=== np.linalg.solve() ===")
print("Sistema 2x2:")
print(" -9x + 4y = 20")
print(" 16x - 7y = 80")
A = np.array([[-9, 4], [16, -7]])
b = np.array([20, 80])
x, y = linalg.solve(A, b)
print(f"x = {x}, y = {y}")
print()

print("Sistema 3x3:")
print("  x - 2y + 3z = 7")
print(" 2x +  y +  z = 4")
print("-3x + 2y - 2z = -10")
A2 = np.array([[1, -2, 3], [2, 1, 1], [-3, 2, -2]])
b2 = np.array([7, 4, -10])
x, y, z = linalg.solve(A2, b2)
print(f"x = {x}, y = {y}, z = {z}")
print()

# 📌 np.matmul() o @ - Multiplicación matricial
print("=== np.matmul() / @ ===")
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print("A:", A, sep="\n")
print("B:", B, sep="\n")
print("A @ B:", A @ B, sep="\n")
print()

# 📌 np.identity() - Matriz identidad
print("=== np.identity() ===")
print("np.identity(4):\n", np.identity(4))

=== np.linalg.solve() ===
Sistema 2x2:
 -9x + 4y = 20
 16x - 7y = 80
x = 460.0, y = 1040.0

Sistema 3x3:
  x - 2y + 3z = 7
 2x +  y +  z = 4
-3x + 2y - 2z = -10
x = 2.0, y = -0.9999999999999998, z = 1.0000000000000002

=== np.matmul() / @ ===
A:
[[1 2]
 [3 4]]
B:
[[5 6]
 [7 8]]
A @ B:
[[19 22]
 [43 50]]

=== np.identity() ===
np.identity(4):
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

## 2.7 Filtrado y condiciones

In [10]:
# 📌 np.where() - Condicional vectorizado
print("=== np.where() ===")
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("arr:", arr)

# Forma 1: Reemplazar valores según condición
arr_where = np.where(arr > 5, 100, arr)  # Si >5 → 100, si no → valor original
print("np.where(arr > 5, 100, arr):", arr_where)

# Forma 2: Obtener índices donde se cumple condición
indices = np.where(arr > 5)  # Devuelve tupla con índices
print("np.where(arr > 5):", indices)
print("arr[np.where(arr > 5)]:", arr[np.where(arr > 5)])  # Valores > 5
print()

# 📌 np.isin() - ¿Está en otro array?
print("=== np.isin() ===")
arr = np.array([1, 2, 3, 4, 5])
print("arr:", arr)
print("np.isin(arr, [2, 4]):", np.isin(arr, [2, 4]))  # [False, True, False, True, False]

=== np.where() ===
arr: [ 1  2  3  4  5  6  7  8  9 10]
np.where(arr > 5, 100, arr): [  1   2   3   4   5 100 100 100 100 100]
np.where(arr > 5): (array([5, 6, 7, 8, 9]),)
arr[np.where(arr > 5)]: [ 6  7  8  9 10]

=== np.isin() ===
arr: [1 2 3 4 5]
np.isin(arr, [2, 4]): [False  True False  True False]

## 2.8 Guardar y cargar

In [11]:
# 📌 np.save() - Guarda un array en .npy
print("=== np.save() ===")
arr = np.array([1, 2, 3, 4, 5])
np.save('mi_array.npy', arr)
print("Array guardado en 'mi_array.npy'")
print()

# 📌 np.load() - Carga un .npy
print("=== np.load() ===")
arr_cargado = np.load('mi_array.npy')
print("arr_cargado:", arr_cargado)
print()

# 📌 np.savez() - Guarda múltiples arrays
print("=== np.savez() ===")
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
np.savez('multiples_arrays.npz', arr1=arr1, arr2=arr2)
print("Arrays guardados en 'multiples_arrays.npz'")
print()

# Cargar múltiples arrays
print("=== Cargar .npz ===")
datos = np.load('multiples_arrays.npz')
print("datos['arr1']:", datos['arr1'])
print("datos['arr2']:", datos['arr2'])

=== np.save() ===
Array guardado en 'mi_array.npy'

=== np.load() ===
arr_cargado: [1 2 3 4 5]

=== np.savez() ===
Arrays guardados en 'multiples_arrays.npz'

=== Cargar .npz ===
datos['arr1']: [1 2 3]
datos['arr2']: [4 5 6]

---
# 🟢 3. PANDAS (`pd`)

## 3.1 Creación de estructuras

In [12]:
# 📌 pd.Series() - Crea una Serie
print("=== pd.Series() ===")
serie = pd.Series([10, 20, 30, 40, 50], index=['a', 'b', 'c', 'd', 'e'])
print("Serie con índice personalizado:")
print(serie)
print()

# 📌 pd.DataFrame() - Crea un DataFrame
print("=== pd.DataFrame() ===")
# Desde diccionario
data = {'Nombre': ['Ana', 'Luis', 'Carlos'], 'Edad': [25, 30, 35]}
df = pd.DataFrame(data)
print("DataFrame desde diccionario:")
display(df)
print()

# Desde lista de diccionarios
data2 = [{'Nombre': 'Ana', 'Edad': 25}, {'Nombre': 'Luis', 'Edad': 30}]
df2 = pd.DataFrame(data2)
print("DataFrame desde lista de diccionarios:")
display(df2)

=== pd.Series() ===
Serie con índice personalizado:
a    10
b    20
c    30
d    40
e    50
dtype: int64

=== pd.DataFrame() ===
DataFrame desde diccionario:

   Nombre  Edad
0     Ana    25
1    Luis    30
2  Carlos    35

DataFrame desde lista de diccionarios:

  Nombre  Edad
0    Ana    25
1   Luis    30

## 3.2 Información y exploración

In [13]:
# Creamos un DataFrame de prueba
df = pd.DataFrame({
    'Nombre': ['Ana', 'Luis', 'Carlos', 'Marta', 'Pedro'],
    'Edad': [25, 30, 35, 28, 40],
    'Ciudad': ['Madrid', 'Barcelona', 'Valencia', 'Sevilla', 'Bilbao'],
    'Salario': [30000, 40000, 35000, 32000, 45000]
})
print("=== DataFrame de prueba ===")
display(df)
print()

# 📌 .head() - Primeras n filas
print("=== .head() ===")
print("df.head(3):")
display(df.head(3))
print()

# 📌 .tail() - Últimas n filas
print("=== .tail() ===")
print("df.tail(2):")
display(df.tail(2))
print()

# 📌 .sample() - Muestra aleatoria
print("=== .sample() ===")
print("df.sample(2):")
display(df.sample(2))
print()

# 📌 .info() - Resumen del DataFrame
print("=== .info() ===")
df.info()
print()

# 📌 .dtypes - Tipos de columnas
print("=== .dtypes ===")
print(df.dtypes)
print()

# 📌 .describe() - Estadísticas descriptivas
print("=== .describe() ===")
display(df.describe())
print()

# 📌 .shape - Dimensiones
print("=== .shape ===")
print("df.shape:", df.shape)
print()

# 📌 .columns - Nombres de columnas
print("=== .columns ===")
print("df.columns:", df.columns)
print()

# 📌 .index - Índice
print("=== .index ===")
print("df.index:", df.index)
print()

# 📌 .values - Array NumPy subyacente
print("=== .values ===")
print("df.values:")
print(df.values)

=== DataFrame de prueba ===

   Nombre  Edad     Ciudad  Salario
0     Ana    25     Madrid    30000
1    Luis    30  Barcelona    40000
2  Carlos    35   Valencia    35000
3   Marta    28    Sevilla    32000
4   Pedro    40     Bilbao    45000

=== .head() ===
df.head(3):

   Nombre  Edad     Ciudad  Salario
0     Ana    25     Madrid    30000
1    Luis    30  Barcelona    40000
2  Carlos    35   Valencia    35000

=== .tail() ===
df.tail(2):

  Nombre  Edad   Ciudad  Salario
3  Marta    28  Sevilla    32000
4  Pedro    40   Bilbao    45000

=== .sample() ===
df.sample(2):

  Nombre  Edad     Ciudad  Salario
1   Luis    30  Barcelona    40000
4  Pedro    40     Bilbao    45000

=== .info() ===
<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Nombre   5 non-null      str
 1   Edad     5 non-null      int64
 2   Ciudad   5 non-null      str
 3   Salario  5 non-null      int64
dtypes: int64(2), str(2)
memory usage: 292.0 bytes

=== .dtypes ===
Nombre       str
Edad       int64
Ciudad       str
Salario    int64
dtype: object

=== .describe() ===

           Edad       Salario
count   5.00000      5.000000
mean   31.60000  36400.000000
std     5.94138   6107.372594
min    25.00000  30000.000000
25%    28.00000  32000.000000
50%    30.00000  35000.000000
75%    35.00000  40000.000000
max    40.00000  45000.000000

=== .shape ===
df.shape: (5, 4)

=== .columns ===
df.columns: Index(['Nombre', 'Edad', 'Ciudad', 'Salario'], dtype='str')

=== .index ===
df.index: RangeIndex(start=0, stop=5, step=1)

=== .values ===
df.values:
[['Ana' 25 'Madrid' 30000]
 ['Luis' 30 'Barcelona' 40000]
 ['Carlos' 35 'Valencia' 35000]
 ['Marta' 28 'Sevilla' 32000]
 ['Pedro' 40 'Bilbao' 45000]]

## 3.3 Selección y filtrado

In [14]:
# DataFrame de prueba
df = pd.DataFrame({
    'Nombre': ['Ana', 'Luis', 'Carlos', 'Marta', 'Pedro'],
    'Edad': [25, 30, 35, 28, 40],
    'Ciudad': ['Madrid', 'Barcelona', 'Valencia', 'Sevilla', 'Bilbao'],
    'Salario': [30000, 40000, 35000, 32000, 45000]
}, index=['a', 'b', 'c', 'd', 'e'])

print("=== DataFrame de prueba ===")
display(df)
print()

# 📌 df['col'] - Selecciona columna (Series)
print("=== df['col'] ===")
print("df['Nombre']:")
print(df['Nombre'])
print()

# 📌 df[['col1','col2']] - Selecciona múltiples columnas
print("=== df[['col1','col2']] ===")
print("df[['Nombre', 'Edad']]:")
display(df[['Nombre', 'Edad']])
print()

# 📌 .loc[] - Selección por etiqueta (inclusivo en slicing)
print("=== .loc[] ===")
print("df.loc['a']:")  # Fila 'a'
print(df.loc['a'])
print()
print("df.loc['a':'c', 'Nombre':'Edad']:")
display(df.loc['a':'c', 'Nombre':'Edad'])  # Filas a-c, columnas Nombre-Edad (inclusivo)
print()

# 📌 .iloc[] - Selección por posición (exclusivo en slicing)
print("=== .iloc[] ===")
print("df.iloc[0]:")  # Primera fila

=== DataFrame de prueba ===

   Nombre  Edad     Ciudad  Salario
a     Ana    25     Madrid    30000
b    Luis    30  Barcelona    40000
c  Carlos    35   Valencia    35000
d   Marta    28    Sevilla    32000
e   Pedro    40     Bilbao    45000

=== df['col'] ===
df['Nombre']:
a       Ana
b      Luis
c    Carlos
d     Marta
e     Pedro
Name: Nombre, dtype: str

=== df[['col1','col2']] ===
df[['Nombre', 'Edad']]:

   Nombre  Edad
a     Ana    25
b    Luis    30
c  Carlos    35
d   Marta    28
e   Pedro    40

=== .loc[] ===
df.loc['a']:
Nombre        Ana
Edad           25
Ciudad     Madrid
Salario     30000
Name: a, dtype: object

df.loc['a':'c', 'Nombre':'Edad']:

   Nombre  Edad
a     Ana    25
b    Luis    30
c  Carlos    35

=== .iloc[] ===
df.iloc[0]: